
@startuml
!define RECTANGLE class

'определение сущности Film'
RECTANGLE Film {
  + Film ID: id
  + Name: string
  + Description: string
}

'определение сущности Session'
'связь 1:N, т.е. у фильма может быть несколько сеансов, но один сеанс - один фильм'
RECTANGLE Session {
  + Session ID: id
  + Film ID: id
  + Date: string
}

'определение сущности Booking'
'связь 1:1, одно бронирование для одного сеанса'
RECTANGLE Booking {
  + Booking number: string
  + Session ID: id
}

Film "0..*" -- "1" Session
Session "1" -- "1" Booking
@enduml
