@startuml
!define RECTANGLE class

RECTANGLE Products {
  + ProductID (PK)
  + Model
  + Color
  + Size
  + ProduxtionDate
  + Cost
}

RECTANGLE Orders {
  + OrderID (PK)
  + ClientName
  + ClientPhone
  + OrderDate
  + Cost
}

RECTANGLE ProductsOrders {
  + OrderID (PK)
  + ProductID
  + Quantity
}

RECTANGLE Material {
  + MaterialID (PK)
  + MaterialName
}

RECTANGLE ProductsMaterials {
  + ProductID (PK)
  + MaterialID (PK)
  + ProductID
  + Quantity
}

RECTANGLE Suppliers {
  + SuppliersID (PK)
  + SuppliersName
  + ContactInfo
}

RECTANGLE Supplies {
  + SuppliersID (PK)
  + MaterialID (PK)
  + Cost
  + SupplyDate
}

Orders " " --> " " ProductsOrders
Products " " --> " " ProductsOrders
Material " " --> " " ProductsMaterials
Products " " --> " " ProductsMaterials
Suppliers " " --> " " Supplies
Material " " --> " " Supplies

@enduml
